### ISSUE TITLE
ipairs error on login crashes addon

### ISSUE THREAD

**Issue by npaganini** [stevin05/CraftScan#1]
Hey, great addon! Just what I needed tbh.
I was using the addon on another computer and just bought a new one and when I tried to install this addon manually (downloaded on curseforge website) I got the following error:
```Message: Interface/AddOns/CraftScan/Settings.lua:35: bad argument #1 to 'ipairs' (table expected, got nil)
Time: Sat Jun 22 00:23:44 2024
Count: 1
Stack: Interface/AddOns/CraftScan/Settings.lua:35: bad argument #1 to 'ipairs' (table expected, got nil)
[string "=[C]"]: ?
[string "=[C]"]: in function `ipairs'
[string "@Interface/AddOns/CraftScan/Settings.lua"]:35: in function <Interface/AddOns/CraftScan/Settings.lua:30>
[string "@Interface/AddOns/CraftScan/Settings.lua"]:164: in function `onLoad'
[string "@Interface/AddOns/CraftScan/Utils/Utils.lua"]:594: in function <Interface/AddOns/CraftScan/Utils/Utils.lua:590>

Locals: (*temporary) = <function> defined =[C]:-1
```
I got it on login and the CraftScan checkbox in the professions wasn't appearing so then I tried installing it through downloading the zip in the repo (main branch) and I still got the same error.
Idk why it wasn't failing in the other computer, but I have used it before to develop an addon in the past, so maybe I already had downloaded a library that you used too.
Hopefully you're able to add the necessary libraries to the addon, since this one was quickly becoming my favorite!

**Comment by stevin05** [comment]
Should be fixed with 1.0.2. Your first computer likely worked because the bug was introduced in a recent change that went on CurseForge on June 9. CurseForge had a bit over a week delay from when I released that to when it pulled the release from github, so you can manually download it here if you don't want to wait for it to be sync'ed over again.
