### ISSUE TITLE
Multiple Items in one chat for Analytics

### ISSUE THREAD

**Issue by AdiSSJ5** [stevin05/CraftScan#12]
Hi, great Idea with the tracking for analytics.
When someone is looking for more than one item only the first one gets tracked though.

**Comment by stevin05** [comment]
It’s supposed to detect all of them. Uses a gmatch in a loop, but forgot to test more than one.

Did both of the items have a quality icon on them? That was the only way I could find to detect crafted items without a manually maintained dictionary of all crafting recipes.

**Comment by stevin05** [comment]
Or if one of the items is an item you can craft, it would only detect that one because it piggy backs on the original scanning if possible, and never bothered to make that multi-item aware.

**Comment by AdiSSJ5** [comment]
He was looking for 5 items. Of which I could craft 3. But only the very first was recorded

**Comment by stevin05** [comment]
Hopefully fixed in 1.2.7
