### ISSUE TITLE
Primär Keywords

### ISSUE THREAD

**Issue by Finlay00** [stevin05/CraftScan#2]
The addon always deletes my primary keywords that I entered manually... I'm playing with the German client and want to change neuherrstellung to recraft and add suche , but when I relog the keywords are gone again
sorry for the stupid English Google translator :D
Greetings

**Comment by stevin05** [comment]
Thanks for the report. Should be fixed in 1.0.3.

If you have any suggestions for better German translations, just list the old text and what to replace it with.
