### ISSUE TITLE
About Chinese keyword matching

### ISSUE THREAD

**Issue by abs15986** [stevin05/CraftScan#21]
I found that there must be spaces between keywords to match them, but Chinese usually has no spaces. Can this problem be solved?
This Addons is awesome!

**Comment by abs15986** [comment]
Can you add it? The Chinese client is really unusable now. It can't remind me of the order, or tell me how to modify the space match. I will adjust it myself. Thank you.

**Comment by stevin05** [comment]
Edit HasMatch in ChatScanner.lua

It’s a gross function that was one of the first things I wrote in lua. Should be easy to rip out the extra conditions looking for spaces.

**Comment by abs15986** [comment]
I changed
```lua
        if b and e and (b == 1 or message:sub(b - 1, b - 1) == ' ' or (b > 2 and message:sub(b - 2, b - 1) == '|r')) and
            (e == #message or message:sub(e + 1, e + 1) == ' ' or message:sub(e + 1, e + 1) == '|') then
``` 
to
```lua
        if b and e then
``` 
It's not working, Am I doing something wrong? 
Sorry, I don't know much about code

**Comment by stevin05** [comment]
That should do it. Have you tested the same message with and without spaces for verify it worked before? Might need to check the keyword configurations. No idea if ChatGPT translated them to something that makes sense.

**Comment by abs15986** [comment]
Yes, I have tested it. 
After I deleted that part of the code, I could not receive any reminders at all. Even the messages with spaces that could be used as reminders before were not reminded. I don't know what went wrong.

**Comment by stevin05** [comment]
After updating to 1.3.8, go to the CraftScan settings in the main bliz settings, and check the bottom option: "Permissive keyword matching", which ChatGPT translated to "宽松的关键词匹配" and "寬鬆的關鍵詞匹配".

**Comment by abs15986** [comment]
It‘s worked!  thanks!
