### ISSUE TITLE
CraftScan options for other accounts without any professions

### ISSUE THREAD

**Issue by Kamian404** [stevin05/CraftScan#31]
It would be very helpful to have access to these options on Chars which dont have any professions:
![grafik](https://github.com/user-attachments/assets/0f0f227a-bb9a-4cab-a95f-ed6178c640e3)

I got two accounts and my twink has no professions. I needed to learn Khaz Algar to activate it. Not a big deal, but anyway.

**Comment by stevin05** [comment]
Lots of the profession APIs only work on characters that have the profession, and I don't want to build/maintain my own database of profession stuff to make it work on other chars.

Also, that page is attached to the character modifying it, so learning the profession on your alt to edit the page won't have any impact on your main crafter's config. CraftScan would think you have two characters with the profession and then you could prioritize one by right clicking on the crafter list and marking one as the 'Primary Crafter'.
