### ISSUE TITLE
No alert sound

### ISSUE THREAD

**Issue by gyurivukman** [stevin05/CraftScan#36]
**Expected behaviour:** 
The selected sound alert plays whenever a notification would appear/The addon successfully detects a crafting request

**Current behaviour:**
No sound plays at all when a notification appears ,even if an alert sound is selected.

**Reproduce:**
With weakauras installed, select an alert sound like Shotgun from the alert sounds and try to trigger the addon with "LF BS" in /say as its explained in the tutorial

**Additional Context:**
I have weakauras installed and in the addon's options, I'm able to select (and hear) a notification sound, however when i trigger the addon manually with a message in say or when the addon picks up a request from trade, the selected alert sound does not play.

**Comment by stevin05** [comment]
On the list of your crafters, are the little headsets on the right side all green? I made it configurable per crafter since I got tired of being spammed on busy nights.

**Comment by gyurivukman** [comment]
okay that solves it:) I wasnt expecting it to contain additional options in its own, rarely visited ui sorry!
ANd thank you for the explanation.

**Comment by stevin05** [comment]
It shows you the list of everything detected so I always check it coming back from afk to see if there are any recent requests.
