### ISSUE TITLE
No sound alerts

### ISSUE THREAD

**Issue by AdiSSJ5** [stevin05/CraftScan#4]
Somehow I don't have any sound alerts. I tried activating and deactivating all sound alerts within the addon and tried also to use different sound warnings.

Edit: works after installing weakaura

**Comment by kevin-netapp** [comment]
Yeah, I assumed everyone would have weakauras, so just registered their list of available sounds as the options. Will add a note to the addon description.

**Comment by stevin05** [comment]
Yeah, I assumed everyone would have WeakAuras, so simply copied over their list of sound paths. Will add a note in the sound alerts tooltip.
