### ISSUE TITLE
Saving concentration amount

### ISSUE THREAD

**Issue by mjoed** [stevin05/CraftScan#40]
could you add an option to display the current concentration amount of each profession for each crafter?

**Comment by stevin05** [comment]
Doesn’t CraftSim already have this?

**Comment by mjoed** [comment]
it does, but i am not using it. but i understand if you don't want to have redundant functionalities if most of the people use both addons

**Comment by stevin05** [comment]
Yeah, going to close this since it already exists somewhere. Most crafters use it, but I guess it’s not that helpful if you only do orders.
