### ISSUE TITLE
Changes request.

### ISSUE THREAD

**Issue by kasiopec** [stevin05/CraftScan#8]
Make UI button resizable/scalable (via options?).
Add button to the minimap and allow disabling UI circle, so that if crafter found i go to minimap icon instead (to avoid polluting UI with bunch of floating stuff)
Opened window at the moment is not draggable? i think edge of the window is clickthrough (even not moving with addons like MoveAny)

**Comment by stevin05** [comment]
Would just scalable be good enough? The UI circle could just become the minimap button and you plop it up wherever on the minimap.

I hate all the minimap buttons and always disable them. I've been avoiding all external libraries to learn the basics, but maybe it's time to pull something in if making it an actual minimap button provides something extra. Looks like that's not a built in bliz thing, so I assume there's some framework that makes them generally manageable.

**Comment by kasiopec** [comment]
i am personally using HidingBar addon that makes all the minimap buttons into hidden mouseover onclick menu. So all icons are in 1 place and not scattered around the minimap :) 

As per scalable i guess sure, we can go that route.
