### ISSUE TITLE
edit proposed greeting

### ISSUE THREAD

**Issue by braiky** [stevin05/CraftScan#9]
Hello 

Could we get the option to change the proposed greeting template? Im german and i think responding in english isnt great.
Adding the german keywords worked fine for me but I cant overwrite the main greeting , my german text just gets added afterwards

Sorry if it allready works somehow to do that - but i cant make it work atm 

greets

**Comment by stevin05** [comment]
Are you running the game client in German? I have ChatGPT generated localizations, so it should be using those. (No idea if they are any good, but it should at least be spitting out bad German.)

Should be easy to add customization options for it though, and I had considered it before, but it’s a little painful with 4 combos combining (item link/profession) and (current char/alt). I guess the translations are probably terrible for trying to deal with those cases anyway though, so probably worth it.

Will come up with some sort of % replacement syntax for the various pieces of available info.

**Comment by braiky** [comment]
Oh ye - Im running the game in english (like a lot of EU guys do ) but the trade chat language is mostly in local language. And I´m afraid it sounds weird for the customer if the response is in english then

**Comment by stevin05** [comment]
Hopefully I made it obvious enough, but you can middle click and type out something short manually until I get this implemented.

**Comment by stevin05** [comment]
Or edit enUS.lua. The entries for the greeting are near the top. Just leave the %s in there to consume the item link, profession name, and/or alt character names

**Comment by braiky** [comment]
alright thanks alot

**Comment by thomasclavet** [comment]
Would love to have this feature as well
Not familiar with LUA but since you already have a bunch of Locales set up, maybe having a dropdown list to choose your desired Locale would be an option?

**Comment by stevin05** [comment]
Fixed in v1.2.1 released an hour or so ago. There is a new button in the top right of the CraftScan page to set your own text.
